version: '3.7'
services:
  dashboard:
     image: housepricepythonuk:dev
     build: 
       context: .
       dockerfile: Dockerfile.dev
     container_name: python_dashboard_dev
     restart: on-failure:1
     ports:
       - "8050:8050"
     volumes:
      # current, loads but doesn't properly update
       - "./app:/home/python/app/"
      # attempt 1, no such file app/processed.csv 
      # - "./app:/home/python/app"
      # attempt 2, loads but doesn't properly update
      # - "./:/home/python/app"
      # attempt 3, failed to find attribute server in app.app
      # - "./:/home/python/app/app"
      # attempt 4, based on front-end, again loads but doesn't work
      # - "/home/python/app/app:/home/python/app/app"
     networks:
       - network 
    
networks:
   network:
     driver: bridge